name: Build and Publish

on: [push, workflow_dispatch]

env:
  DOTNET_VERSION: '9.x'
  
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
    
      - name: Setup .NET Core ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Install dependencies
        run: |
          dotnet nuget add source https://nuget.pkg.github.com/EinQuadrat/index.json --name GitHub -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text
          dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Pack
        run: dotnet pack --configuration Release --no-restore

      - name: Publish
        run: dotnet nuget push **/*.nupkg --source "GitHub" --api-key ${{ secrets.GITHUB_TOKEN }} --skip-duplicate
